### ISSUE TITLE
Ignore Messages Where Bot Isn't First

### ISSUE THREAD

**Issue by mrxinu** [bketelsen/gcbot#1]
![image](https://user-images.githubusercontent.com/6706/98830401-3a778780-23ef-11eb-925c-1935daa9295b.png)

**Comment by bketelsen** [comment]
that should be an easy one to fix... *hint*

**Comment by mrxinu** [comment]
I'm on it as soon as Mackenzie goes down.

**Comment by SteelPhase** [comment]
Note for future sanity. This would only affect users with permission to mention the configured role
